### ISSUE TITLE
Offering Help

### ISSUE THREAD

**Issue by tyagow** [localstack/chalice-local#1]
Thank you soooo much for creating this tool, I am struggling for a few days trying to connect my lambdas to sqs events on localstack...
I want to offer help to maintain this project and I think a good starting point would be documenting the setup process, so if you help me here with the steps I can submit a PR with detailed steps in the README.md file.

Thanks again for starting this project, I am looking forward to contributing in any way I can

**Comment by tyagow** [comment]
Is the goal to use something like `chalice-local deploy --stage local` ?

**Comment by whummer** [comment]
Hi @tyagow , thanks for the feedback and for offering your help. Can you please share some details about your requirement - do you have a sample project that we can try to get deployed via `chalice-local`? Please keep us posted - any help or pull requests would be much appreciated, thanks.

I think the goal would be to simply support this command (without the `--stage local` flag) - what do you think?
```
chalice-local deploy
```

**Comment by tyagow** [comment]
Hey thanks for the reply @whummer, for the project I am working on I need to use `--stage local` because we have several stages, and we use some environment-specific configurations for each stage that don't apply to local environment, one example is on our `.chalice/config.json` we have for dev environment:
```
        "local": {
            "environment_variables": {"ENV": "local"},
            "api_gateway_stage": "local"
        },
        "dev": {
            "environment_variables": {"ENV": "dev"},
            "api_gateway_stage": "dev",
            "api_gateway_custom_domain": {
                "domain_name": "dev-chalice.REDACTED.com",
                "certificate_arn": "arn:aws:acm:us-east-1:REDACTED:certificate/7d96394fREDACTED"
            }
        }
```

**Comment by whummer** [comment]
Ok - thanks for clarifying the use of the stage parameter. In my understanding, this should work with this plugin (as it is only a simple wrapper that reconfigures endpoints) - but please feel free to open any follow-up issues if the problem persists. Thanks for your help!
